name: Build and Release Lottery Generator

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            artifact-name: loteria-gerador-linux
            # O separador de dados para PyInstaller no Linux é ":"
            data-separator: ":"
          - os: windows-2022
            platform: windows
            artifact-name: loteria-gerador.exe
            # O separador de dados para PyInstaller no Windows é ";"
            data-separator: ";"

    runs-on: ${{ matrix.os }}
    env:
      PYTHONUTF8: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Dependências do sistema para o backend WebView do Flet (WebKitGTK)
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev

      - name: Install Poetry
        run: pip install poetry

      # Instala dependências do projeto, incluindo flet_desktop e pyinstaller
      - name: Install project dependencies
        run: poetry install --no-root

      # Gera o executável com PyInstaller (substituindo o "flet build")
      # --- ESTA É A ÚNICA SEÇÃO ALTERADA ---
      - name: Build executable with PyInstaller
        run: >
          poetry run pyinstaller --name loteria-gerador --onefile --windowed
          --add-data "src/assets${{ matrix.data-separator }}assets"
          --paths "src" src/main.py

      - name: List build output
        run: ls -R dist

      # Faz o upload do executável final
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: dist/${{ matrix.artifact-name }}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "Automated release with builds for Linux and Windows."
          draft: false
          prerelease: false
          files: |
            dist/linux-build/loteria-gerador-linux
            dist/windows-build/loteria-gerador.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}