name: Build and Release Lottery Generator

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            # --- NOME FINAL DESEJADO PARA LINUX ---
            artifact-name: loteria-gerador-linux
            data-separator: ":"
          - os: windows-2022
            platform: windows
            # --- NOME FINAL DESEJADO PARA WINDOWS ---
            artifact-name: loteria-gerador.exe
            data-separator: ";"

    runs-on: ${{ matrix.os }}
    env:
      PYTHONUTF8: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev

      - name: Install Poetry
        run: pip install poetry

      - name: Install project dependencies
        run: poetry install --no-root

      # --- ETAPA DE BUILD ALTERADA ---
      - name: Build executable with PyInstaller
        # Usamos 'if' para ter comandos específicos por OS
        shell: bash
        run: |
          # Comando base para o PyInstaller
          BASE_CMD="poetry run pyinstaller --name loteria-gerador --onefile --windowed --add-data 'src/assets${{ matrix.data-separator }}assets' --paths 'src' src/main.py"

          # Executa o comando de build
          $BASE_CMD

          # Passo extra APENAS para Linux: Renomeia o arquivo gerado
          if [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
            echo "Renaming Linux executable..."
            mv dist/loteria-gerador dist/loteria-gerador-linux
          fi

      - name: List build output
        run: ls -R dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: dist/${{ matrix.artifact-name }}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "Automated release with builds for Linux and Windows."
          draft: false
          prerelease: false
          files: |
            # --- NOMES FINAIS PARA A RELEASE ---
            dist/linux-build/loteria-gerador-linux
            dist/windows-build/loteria-gerador.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}