name: Build and Release Lottery Generator

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        include:
          - os: ubuntu-22.04
            platform: linux
            build-command: poetry run flet build linux
            artifact-path: dist/lottery_generator
          - os: windows-2022
            platform: windows
            build-command: poetry run flet build windows
            artifact-path: dist/lottery_generator.exe

    runs-on: ${{ matrix.os }}
    env:
      PYTHONUTF8: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Linux dependencies
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libunwind-dev curl unzip git xz-utils

      # Windows dependencies
      - name: Install Windows dependencies
        if: matrix.os == 'windows-2022'
        run: pip install pywin32

      - name: Install Poetry
        run: pip install poetry

      - name: Install project dependencies
        run: poetry install --no-root

      # Flutter installation Linux
      - name: Install Flutter on Linux
        if: matrix.os == 'ubuntu-22.04'
        shell: bash
        run: |
          curl -sSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.2-stable.tar.xz -o flutter.tar.xz
          tar xf flutter.tar.xz -C $RUNNER_TEMP
          export FLET_FLUTTER_PATH=$RUNNER_TEMP/flutter
          echo "$FLET_FLUTTER_PATH/bin" >> $GITHUB_PATH

      # Flutter installation Windows
      - name: Install Flutter on Windows
        if: matrix.os == 'windows-2022'
        run: choco install flutter --version 3.29.2 -y

      - name: Verify Flutter version
        run: flutter --version

      - name: Build Flet executable
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
            export FLET_FLUTTER_PATH=$RUNNER_TEMP/flutter
          fi
          ${{ matrix.build-command }}

      - name: List build output
        shell: bash
        run: dir dist || ls -R dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: ${{ matrix.artifact-path }}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Display structure of downloaded files
        run: ls -R dist
        shell: bash

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "Automated release with builds for Linux and Windows."
          draft: false
          prerelease: false
          files: |
            dist/linux-build/lottery_generator
            dist/windows-build/lottery_generator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
