name: Build and Release Lottery Generator

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        include:
          - os: ubuntu-22.04
            platform: linux
            build-command: poetry run flet build linux
            artifact-path: dist/lottery_generator
          - os: windows-2022
            platform: windows
            build-command: poetry run flet build windows
            artifact-path: dist/lottery_generator.exe

    runs-on: ${{ matrix.os }}
    env:
      PYTHONUTF8: "1"
      FLET_NO_AUTO_FLUTTER: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Dependências Linux
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libunwind-dev curl unzip git xz-utils
        shell: bash

      # Dependências Windows
      - name: Install Windows dependencies
        if: matrix.os == 'windows-2022'
        run: pip install pywin32
        shell: pwsh

      # Instalação do Poetry
      - name: Install Poetry
        run: pip install poetry
        shell: bash

      # Instala dependências do projeto
      - name: Install project dependencies
        run: poetry install --no-root
        shell: bash

      # Instalação do Flutter
      - name: Install Flutter (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          curl -sSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.35.3-stable.tar.xz -o flutter.tar.xz
          tar xf flutter.tar.xz -C ${{ runner.temp }}
          echo "${{ runner.temp }}/flutter/bin" >> $GITHUB_PATH
          export FLET_FLUTTER_PATH=${{ runner.temp }}/flutter
        shell: bash

      - name: Install Flutter (Windows)
        if: matrix.os == 'windows-2022'
        run: choco install flutter -y
        shell: pwsh

      # Verifica versão do Flutter
      - name: Verify Flutter version
        run: flutter --version
        shell: bash

      # Build do app Flet
      - name: Build Flet executable
        run: ${{ matrix.build-command }}
        shell: bash

      # Lista saída da build
      - name: List build output
        run: ls -R dist
        shell: bash

      # Upload do artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: ${{ matrix.artifact-path }}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Display structure of downloaded files
        run: ls -R dist
        shell: bash

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "Automated release with builds for Linux and Windows."
          draft: false
          prerelease: false
          files: |
            dist/linux-build/lottery_generator
            dist/windows-build/lottery_generator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
