name: Build and Release Lottery Generator

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        include:
          - os: ubuntu-22.04
            platform: linux
            build-command: poetry run flet build desktop --platform linux
            artifact-path: dist/lottery_generator
          - os: windows-2022
            platform: windows
            build-command: poetry run flet build desktop --platform windows
            artifact-path: dist/lottery_generator.exe

    runs-on: ${{ matrix.os }}
    env:
      PYTHONUTF8: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install Windows dependencies (optional)
        if: matrix.os == 'windows-2022'
        run: |
          pip install pywin32  # Optional: Add Windows-specific dependencies if needed

      - name: Install Poetry
        run: pip install poetry

      - name: Install project dependencies
        run: poetry install

      - name: Build Flet executable
        run: ${{ matrix.build-command }}

      - name: List build output
        run: dir dist || ls -R dist
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: ${{ matrix.artifact-path }}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Display structure of downloaded files
        run: ls -R dist
        shell: bash

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "Automated release with builds for Linux and Windows."
          draft: false
          prerelease: false
          files: |
            dist/linux-build/lottery_generator
            dist/windows-build/lottery_generator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}